version: '3'

tasks:
  run:
    cmds:
      - uv run python manage.py runserver 8989

  dev:
    cmds:
      - npm run dev

  build:
    cmds:
      - npm run build

  migrate:
    cmds:
      - uv run python manage.py makemigrations
      - uv run python manage.py migrate

  reset:
    cmds:
      - find address cart company discount goods invite mp order payment person price review transaction warehouse -type f -path '*/migrations/*.py' ! -name '__init__.py' -print -delete
      - rm -f DB/db.sqlite3
      - uv run python manage.py makemigrations
      - uv run python manage.py migrate
      - uv run python manage.py loaddata sample_data.json
