# Generated by Django 6.0.7 on 2026-07-25 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_ids', models.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('authorization', 'Authorization'), ('capture', 'Capture')], max_length=32)),
                ('method', models.CharField(blank=True, choices=[('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('gift_card', 'Gift card'), ('wallet', 'Wallet')], max_length=32, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.IntegerField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'GBP')])),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('provider', models.CharField(blank=True, max_length=64, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
