# Generated by Django 6.0.7 on 2026-07-25 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_ids', models.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_ids', models.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('vintage_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('grape_variety', models.CharField(blank=True, max_length=255, null=True)),
                ('volume_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('abv', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.IntegerField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'GBP')])),
                ('barcode', models.CharField(blank=True, max_length=64, null=True)),
                ('planted', models.DateField(blank=True, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=255, null=True)),
                ('elevation', models.PositiveIntegerField(blank=True, null=True)),
                ('slope', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('harvested', models.DateField(blank=True, null=True)),
                ('organic_certified', models.BooleanField(default=False)),
                ('wine_type', models.CharField(blank=True, choices=[('still', 'Still'), ('sparkling', 'Sparkling'), ('fortified', 'Fortified'), ('dessert', 'Dessert'), ('rose', 'Rosé')], max_length=16, null=True)),
                ('food_pairing', models.TextField(blank=True, null=True)),
                ('awards', models.JSONField(blank=True, default=list)),
                ('available_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('min_order_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In stock'), ('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock'), ('pre_order', 'Pre-order')], default='in_stock', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='company.company')),
                ('groups', models.ManyToManyField(blank=True, related_name='goods', to='goods.goodgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_ids', models.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='goods.good')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='good',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='goods.goodphoto'),
        ),
    ]
