# Generated by Django 6.0.7 on 2026-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='sugar_level',
            field=models.IntegerField(blank=True, choices=[(3, 'Brut Nature'), (6, 'Extra Brut'), (12, 'Brut'), (17, 'Extra Dry (Extra Sec)'), (32, 'Sec'), (50, 'Demi-Sec'), (51, 'Doux')], null=True),
        ),
    ]
