# Generated by Django 6.0.7 on 2026-07-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_language',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
