# Generated by Django 6.0.7 on 2026-07-25 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_ids', models.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=64, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=64, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('annual_production', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('verified_seller', models.BooleanField(default=False)),
                ('dispute_count', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('founders', models.JSONField(blank=True, default=list)),
                ('ownership_info', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('awards', models.JSONField(blank=True, default=list)),
                ('languages_spoken', models.JSONField(blank=True, default=list)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_position', models.CharField(blank=True, max_length=255, null=True)),
                ('support_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_address', models.TextField(blank=True, null=True)),
                ('operational_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=32, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('iban', models.CharField(blank=True, max_length=64, null=True)),
                ('swift_bic', models.CharField(blank=True, max_length=32, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=64, null=True)),
                ('preferred_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('pr_website', models.URLField(blank=True, null=True)),
                ('press_kit_url', models.URLField(blank=True, null=True)),
                ('sustainability_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_ids', models.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('winery', 'Winery'), ('vineyard', 'Vineyard'), ('cellar', 'Cellar'), ('other', 'Other')], default='other', max_length=16)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='hero_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.companyphoto'),
        ),
    ]
