# Generated by Django 6.0.7 on 2026-07-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='preferred_currency',
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'GBP')], default=1),
        ),
    ]
