# Generated by Django 6.0.7 on 2026-07-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_preferred_currency_company_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.IntegerField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'GBP')], default=1),
        ),
    ]
